sonar.projectKey=evat
sonar.projectName=EVAT
sonar.projectVersion=1.0

sonar.sources=client/web-app/src,server/node-api/src,server/python-services

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/__pycache__/**,**/*.test.ts,**/*.test.tsx,**/test/**,**/tests/**

sonar.tests=server/node-api/test
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=client/web-app/coverage/lcov.info,server/node-api/coverage/lcov.info

sonar.sourceEncoding=UTF-8